package com.smsc.management.app.broadcast.processor;

import com.smsc.management.app.broadcast.model.entity.Broadcast;
import com.smsc.management.exception.FileProcessingException;

import java.io.InputStream;

public interface BroadcastFileProcessor {

    /**
     * Processes the input file to generate messages for a broadcast.
     *
     * @param inputStream  The uploaded file input stream.
     * @param fileId       The autogenerated ID associated with the uploaded file.
     * @param broadcast    The associated broadcast entity.
     * @param batchSize    The number of records to process per batch.
     * @param hasHeaders   Indicates whether the file contains a header row.
     * @param delimiter    The delimiter used to separate columns in CSV/TXT files (ignored for non-delimited files like Excel).
     */
    void process(InputStream inputStream, int fileId, Broadcast broadcast, int batchSize, boolean hasHeaders, String delimiter);

    /**
     * Indicates whether this processor supports the given file type.
     * This can be determined by file extension or content type.
     *
     * @param fileType The type or name of the file (extension or MIME type).
     * @return true if the processor supports this file type.
     */
    boolean supports(String fileType);

    /**
     * Reads the file to extract column names from the header or generates generic names (Column01, Column02...).
     *
     * @param inputStream   The uploaded file input stream.
     * @param detectHeader  If true, uses the first line as header; otherwise generates generic column names.
     * @param delimiter     The delimiter used to separate columns in CSV/TXT files (ignored for non-delimited files like Excel).
     * @return A comma-separated string representing the column headers.
     */
    String extractColumns(InputStream inputStream, boolean detectHeader, String delimiter) throws FileProcessingException;
}