package com.smsc.management.app.broadcast.component;

import com.smsc.management.app.broadcast.model.entity.Broadcast;
import com.smsc.management.app.broadcast.model.entity.BroadcastFile;
import com.smsc.management.app.broadcast.model.repository.BroadcastFileRepository;
import com.smsc.management.app.broadcast.processor.BroadcastFileProcessor;
import com.smsc.management.app.broadcast.utils.BroadcastStatus;
import com.smsc.management.app.broadcast.utils.CopyManagerFactory;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.postgresql.copy.CopyManager;
import org.springframework.stereotype.Component;

import javax.sql.DataSource;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.util.List;

@Slf4j
@Component
@RequiredArgsConstructor
public class BroadcastFileTask {

    private final List<BroadcastFileProcessor> fileProcessors;
    private final DataSource dataSource;
    private final BroadcastFileRepository broadcastFileRepository;
    private final CopyManagerFactory copyManagerFactory;

    /**
     * Processes the uploaded file asynchronously and stores the message data extracted from it.
     * The file should have the following format for each record:
     * <ul>
     *     <li>0 - Source address</li>
     *     <li>1 - Source TON (Type of Number)</li>
     *     <li>2 - Source NPI (Numbering Plan Indicator)</li>
     *     <li>3 - Destination address</li>
     *     <li>4 - Destination TON (Type of Number)</li>
     *     <li>5 - Destination NPI (Numbering Plan Indicator)</li>
     *     <li>6 - Message text</li>
     * </ul>
     *
     * @param inputStream The input stream containing the file data to be processed.
     * @param filename    The name of the uploaded file.
     * @param fileId      The autogenerated ID associated with the uploaded file.
     * @param broadcast   The broadcast object created.
     * @param batchSize   The number of records to be processed per batch.
     */
    public void processFileAsync(InputStream inputStream, String filename, int fileId, Broadcast broadcast, int batchSize, boolean hasHeaders, String delimiter) {
        log.info("Starting broadcast file processing for broadcastId: {}, file: {}", broadcast.getId(), filename);

        BroadcastFileProcessor processor = fileProcessors.stream()
                .filter(p -> p.supports(filename))
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException("Unsupported file format: " + filename));

        processor.process(inputStream, fileId, broadcast, batchSize, hasHeaders, delimiter);
    }

    public void generateCSVFile(File path, int broadcastId, BroadcastFile broadcastFile) {
        log.debug("Process to create logs for broadcastId {} started.", broadcastId);
        BroadcastStatus status = BroadcastStatus.CREATED;

        String sql = String.format("""
            COPY (
                SELECT
                    broadcast_id,
                    message_id,
                    enqueue_at AS enqueue_date,
                    sent_at AS sent_date,
                    source_addr,
                    destination_addr,
                    CASE
                        WHEN status = 3 THEN 'SENT'
                        WHEN status = 4 THEN 'FAILED'
                        WHEN status = 5 THEN 'DUPLICATED'
                        WHEN status = 6 THEN 'INVALID'
                        ELSE 'ENQUEUE'
                    END AS state,
                    message,
                    comment,
                    dest_protocol,
                    dest_network_id,
                    dest_network_type,
                    dest_name
                FROM broadcast_devices
                WHERE broadcast_id = %d
            ) TO STDOUT WITH (FORMAT CSV, DELIMITER '|', HEADER TRUE, ENCODING 'UTF8')
        """, broadcastId);

        try (
                var connection = dataSource.getConnection();
                var outputStream = new FileOutputStream(path);
                var writer = new OutputStreamWriter(outputStream, StandardCharsets.UTF_8)
        ) {
            CopyManager copyManager = copyManagerFactory.create(connection);
            copyManager.copyOut(sql, writer);

        } catch (Exception e) {
            log.error("Error generating CSV file with COPY TO STDOUT", e);
            status = BroadcastStatus.FAILED;
        }

        broadcastFile.setStatus(status);
        broadcastFileRepository.save(broadcastFile);

        log.debug("Process to create logs for broadcastId {} finished.", broadcastId);
    }

}
