<?xml version="1.0"?>
<project name="smsc.management.backend.release" default="release" basedir=".">
    <property environment="sys"/>
    <property name="release.dir" location="${ant.file.smsc.management.backend.release}/../target" />
    <property name="base.dir" location="${ant.file.smsc.management.backend.release}/.." />
    <property name="bin.dir" location="${release.dir}/bin" />
    <property name="conf.dir" location="${release.dir}/conf" />
    <property name="logs.dir" location="${release.dir}/logs" />
    <property name="checkout.dir" value="${base.dir}/checkout" />
    <property name="smsc.management.backend.release.version" value="3.2.0-SNAPSHOT" />
    <property name="checkout.smsc.management.backend.dir" value="${base.dir}/.." />

    <property name="release.build.goals" value="clean install -Dmaven.test.skip=true" />

    <condition property="mvn.executable" value="${sys.M2_HOME}\bin\mvn.bat" else="mvn">
        <os family="windows"/>
    </condition>

    <target name="release" depends="clean,build,copy,make-final-zip" />

    <target name="clean">
        <echo>Delete ${release.dir}</echo>
        <delete dir="${release.dir}"/>
        <delete dir="${release.dir}/bin"/>
        <delete dir="${release.dir}/conf"/>
        <delete dir="${release.dir}/logs"/>
        <delete>
            <fileset dir="${base.dir}">
                <include name="SMSC_MANAGEMENT_BACKEND-*.*" />
            </fileset>
        </delete>
    </target>

    <target name="build">
        <echo>building SMSC-MANAGEMENT-BACKEND in ${checkout.smsc.management.backend.dir} and ${release.build.goals}</echo>
        <exec failonerror="true" executable="${mvn.executable}" dir="${checkout.smsc.management.backend.dir}">
            <arg line="${release.build.goals}" />
        </exec>

        <copy overwrite="true" todir="${release.dir}/bin">
            <fileset file="${base.dir}/../target/*.jar" />
        </copy>

        <copy failonerror="true" todir="${release.dir}/conf">
            <fileset file="${base.dir}/../src/main/resources/*.properties"/>
        </copy>

        <copy failonerror="true" todir="${release.dir}/conf">
            <fileset file="${base.dir}/../src/main/resources/*.xml"/>
        </copy>

        <copy failonerror="true" todir="${release.dir}/bin">
            <fileset file="${base.dir}/start.sh"/>
        </copy>

        <replace file="${release.dir}/bin/start.sh" token="VERSION" value="${smsc.management.backend.release.version}"/>
    </target>

    <target name="copy">
        <mkdir dir="${release.dir}/bin" />
        <mkdir dir="${release.dir}/conf" />
        <mkdir dir="${release.dir}/logs" />
    </target>

    <target name="make-final-zip" depends="set-time-stamp">
        <zip destfile="${base.dir}/SMSC_MANAGEMENT_BACKEND-${smsc.management.backend.release.version}.zip" filesonly="false">
            <zipfileset dir="${release.dir}" prefix="SMSC_MANAGEMENT_BACKEND-${smsc.management.backend.release.version}">
                <include name="**" />
            </zipfileset>
        </zip>
    </target>

    <target name="set-time-stamp" unless="skip.timestamp">
        <tstamp>
            <format property="time.stamp" pattern="yyMMddHHmm" />
        </tstamp>
    </target>

</project>